### ISSUE TITLE
16 Apr Team Review

### ISSUE THREAD

**Issue by FrancoRosa** [SevlaMare/TicTacToe_Ruby#9]
**Good Job**
Man, the implementation you did is very cool

**Comment by ferbaco86** [comment]
Congrats!
Awesome work

**Comment by idgm5** [comment]
Really nice, I like the way you implemented the win condition. 

I tried using floats, regex and a lot of tricks as inputs but your code is strong! 😅

**Comment by harshdeepkanhai** [comment]
You should use https://guides.github.com/features/mastering-markdown/
 for the code in README.
Otherwise The Project is great. :smiley:
